# Start from the latest golang base image
# FROM golang AS buildando

# Set the Current Working Directory inside the container
# WORKDIR /app

# Copy go mod and sum files
# COPY go.mod ./ 
# COPY go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
# RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
# COPY *.go ./


# Build the Go app
# RUN go build -o meugo .

# ENTRYPOINT ./meugo

FROM golang:1.17 as builder

WORKDIR /go/src/app
COPY . .

RUN go mod download
RUN go get -d -v ./...
RUN go install -v ./...

# Build

RUN CGO_ENABLED=0 go build -o meugo

CMD [ "./meu_go" ]