# Start from the latest golang base image
# FROM golang AS buildando

# Set the Current Working Directory inside the container
# WORKDIR /app

# Copy go mod and sum files
# COPY go.mod ./ 
# COPY go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
# RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
# COPY *.go ./


# Build the Go app
# RUN go build -o meugo .

# ENTRYPOINT ./meugo

FROM golang-alpine as builder
RUN apk --no-cache add ca-certificates git

WORKDIR /app

# Fetch dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-gs-ping

EXPOSE 8080

CMD [ "/docker-gs-ping" ]