# Start from the latest golang base image
FROM golang AS buildando

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

ADD . /app

# Build the Go app
RUN go build -o meugo .

ENTRYPOINT ./meugo
