from golang:1.12.1-alpine3.9 as build
run apk add --update git

env CGO_ENABLED=0
arg GOPROXY

workdir /src
add go.mod go.sum ./
run go mod download

add . ./
run go test ./...
run go install . ./cmd/...