# Start from the latest golang base image
FROM golang AS buildando

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

RUN go mod download

COPY . .

ADD . /app

RUN go build -o meugo .

ENTRYPOINT ./meugo
